import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className=" p-8 flex justify-center w-full bg-sky-500">
          <h1 className="font-sans text-white text-2xl">
            <Link href="/">Learn Next.js</Link>{" "}
          </h1>
        </div>
        <div className="flex justify-center m-10">{children}</div>
      </body>
    </html>
  );
}
